POST http://127.0.0.1:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin2@mail.com",
    "password": "admin254321"
}


#### registro
POST http://127.0.0.1:3000/api/v1/auth/register
Content-Type: application/json

{
    "name": "admin2",
    "email": "admin2@mail.com",
    "password": "admin254321"
}


### perfil 
GET http://127.0.0.1:3000/api/v1/auth/profile

### salir

POST  http://127.0.0.1:3000/api/v1/auth/logout
