GET http://127.0.0.1:3000/api/v1/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJuaWVsc0BtYWlsLmNvbSIsInRpbWUiOiIyMDI2LTA0LTIyVDE5OjMyOjUyLjQ2MloiLCJpYXQiOjE3NzY4ODYzNzIsImV4cCI6MTc3Njg4OTk3Mn0.nxJPDTTfnYfmwnQcUW9AgZ-u3T08tgIeGqHd51trHmI